version: 2
jobs:
  build:
    working_directory: /go/grpc-web-go-client
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout

      - run:
          name: build
          command: CGO_ENABLED=0 go build ./grpcweb

      - run:
          name: test
          command: CGO_ENALBED=0 go test -v -race ./grpcweb
